# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_auto_20170831_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='评论者')),
                ('email', models.EmailField(max_length=254, verbose_name='评论者邮箱')),
                ('text', models.TextField(verbose_name='评论者邮箱')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='评论文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
