# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170831_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='post',
            name='read_nums',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
